//Event Types
export const GET_EVENT_TYPES = "GET_EVENT_TYPES";
export const GET_EVENT_TYPES_SUCCESS = "GET_EVENT_TYPES_SUCCESS";
export const GET_EVENT_TYPES_FAIL = "GET_EVENT_TYPES_FAIL";
export const UPDATE_EVENT_TYPES = "UPDATE_EVENT_TYPES";
export const UPDATE_EVENT_TYPES_SUCCESS = "UPDATE_EVENT_TYPES_SUCCESS";
export const UPDATE_EVENT_TYPES_FAIL = "UPDATE_EVENT_TYPES_FAIL";
export const ADD_EVENT_TYPES = "ADD_EVENT_TYPES";
export const ADD_EVENT_TYPES_SUCCESS = "ADD_EVENT_TYPES_SUCCESS";
export const ADD_EVENT_TYPES_FAIL = "ADD_EVENT_TYPES_FAIL";

//Login
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

//User
export const GET_USER_DETAILS="GET_USER_DETAILS";
export const GET_USER_DETAILS_SUCCESS="GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAIL="GET_USER_DETAILS_FAIL";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const RESET_AUTH = "RESET_AUTH";

//Schedule Events
export const GET_SCHEDULED_EVENTS = "GET_SCHEDULED_EVENTS";
export const GET_SCHEDULED_EVENTS_SUCCESS = "GET_SCHEDULED_EVENTS_SUCCESS";
export const GET_SCHEDULED_EVENTS_FAILURE = "GET_SCHEDULED_EVENTS_FAILURE";

export const CREATE_SCHEDULE_EVENTS = "CREATE_SCHEDULE_EVENTS";
export const CREATE_SCHEDULE_EVENTS_SUCCESS = "CREATE_SCHEDULE_EVENTS_SUCCESS";
export const CREATE_SCHEDULE_EVENTS_FAILURE = "CREATE_SCHEDULE_EVENTS_FAILURE";
export const RESET_APPOINTMENTS="RESET_APPOINTMENTS";